name: Notifications CI

on: [ push, pull_request ]

jobs:
  cs_and_tests:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version: [ '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3' ]

    runs-on: ${{ matrix.os }}

    name: PHP ${{ matrix.php-version }} on ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json, mysqli, mbstring, zip

      - name: Install dependencies with caching
        uses: kagg-design/composer-install@v2

      - name: Run code sniffer
        run: vendor/bin/phpcs --colors

      - name: Run ESLint
        if: ${{ matrix.php-version == '8.3' }}
        run: |
          corepack enable
          yarn set version stable
          yarn
          yarn dev
          yarn lint
